name: Sample

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o ${{ github.workspace }}/demo 

    - name: Upload App
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ${{ github.workspace }}//demo

    - name: Upload Terraform
      uses: actions/upload-artifact@v1
      with:
        name: terraform
        path: ${{ github.workspace }}/appservice


  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest

    environment:
      name: dev

    needs: build
    steps:
      - run: echo "Hello World"    